In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import pyplot
import numpy as np
import warnings

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
PATH_DATA='../data/raw/'
PATH_DATA_INTERIM='../data/interim/'

In [5]:
df1 = pd.read_csv(PATH_DATA_INTERIM+'iter1_interim_cln.csv')

In [6]:
df1.sample()

id                     time         street  median_length  \
17786  34196292  2022-07-17 13:00:00.000  HM Syarifudin          362.0   

       median_delay  median_speed_kmh  total_records  level  \
17786         126.0               6.6              9      3   

                     time2  hours  ...                            streettime2  \
17786  2022-07-17 13:00:00     13  ...  HM Syarifudin_2022-07-17 13:00:00.000   

      is_train weekendmean  weekendstd  weekdaysmean  weekdaysstd  \
17786        1         2.0    0.816497           0.0          0.0   

       weekdaysmean69  weekdaysstd69  weekdaysmean1518  weekdaysstd1518  
17786             0.0            0.0               0.0              0.0  

[1 rows x 22 columns]

In [7]:
df1.columns

Index(['id', 'time', 'street', 'median_length', 'median_delay',
       'median_speed_kmh', 'total_records', 'level', 'time2', 'hours',
       'is_weekend', 'streettime', 'streettime2', 'is_train', 'weekendmean',
       'weekendstd', 'weekdaysmean', 'weekdaysstd', 'weekdaysmean69',
       'weekdaysstd69', 'weekdaysmean1518', 'weekdaysstd1518'],
      dtype='object')

In [8]:
col_used = list(set(df1.columns)-set(['id','is_train','level','time','time2','street','streettime','streettime2']))

col_used.sort() ## --> remember to sort

In [9]:
Xtrain = df1[df1.is_train == 1][col_used]
Ytrain = df1[df1.is_train == 1]['level']

Xtest = df1[df1.is_train == 0][col_used]
Ytest = df1[df1.is_train == 0]['level']

In [10]:
Ytrain.mean(), Ytest.mean()

(2.4188851447968864, 2.429523525315826)

Transformation

In [11]:
SS = StandardScaler()

In [12]:
SS.fit(Xtrain)
Xtrain_ss = pd.DataFrame(SS.transform(Xtrain), columns = col_used)
Xtest_ss = pd.DataFrame(SS.transform(Xtest), columns = col_used)

In [13]:
logisticregression1 = LogisticRegression().fit(Xtrain_ss, Ytrain)

c:\Users\ramad\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
y_train1=logisticregression1.predict(Xtrain_ss)

print('Classification report:\n', classification_report(Ytrain, y_train1))
conf_mat = confusion_matrix(Ytrain, y_train1)
print('Confusion matrix:\n', conf_mat)

Classification report:
               precision    recall  f1-score   support

           1       0.78      0.77      0.78     15941
           2       0.73      0.76      0.75     28139
           3       0.76      0.74      0.75     24215
           4       0.82      0.77      0.79     10970
           5       1.00      1.00      1.00      1158

    accuracy                           0.76     80423
   macro avg       0.82      0.81      0.81     80423
weighted avg       0.76      0.76      0.76     80423

Confusion matrix:
 [[12350  3478    85    28     0]
 [ 3369 21456  3218    96     0]
 [  192  4364 17933  1726     0]
 [   12    36  2503  8419     0]
 [    4     0     0     0  1154]]


In [15]:
y_pred1=logisticregression1.predict(Xtest_ss)

print('Classification report:\n', classification_report(Ytest, y_pred1))
conf_mat = confusion_matrix(Ytest, y_pred1)
print('Confusion matrix:\n', conf_mat)

Classification report:
               precision    recall  f1-score   support

           1       0.74      0.73      0.74      3891
           2       0.70      0.75      0.73      7080
           3       0.74      0.72      0.73      6072
           4       0.81      0.73      0.76      2734
           5       1.00      0.99      1.00       329

    accuracy                           0.74     20106
   macro avg       0.80      0.78      0.79     20106
weighted avg       0.74      0.74      0.74     20106

Confusion matrix:
 [[2857 1006   18   10    0]
 [ 933 5324  798   25    0]
 [  57 1236 4343  436    0]
 [   5   36  708 1985    0]
 [   3    0    0    0  326]]
